import { projectToolbar } from './uiToolbarHarness'
import { projectSettings } from './uiSettingsHarness'
import type { Page } from '@playwright/test'
import { projectAgents } from './uiAgentsHarness'
import { projectComposer } from './uiComposerHarness'
import { projectConversation } from './uiConversationHarness'
import { readFileSync } from 'node:fs'
const shellFixtures = JSON.parse(readFileSync(new URL('./fixtures/ui-shell.json', import.meta.url), 'utf8')) as Array<{
  state: Record<string, unknown>; view: Record<string, unknown>; transitions: Record<string, number>
}>

export async function installMockRemote(page: Page): Promise<void> {
  await page.exposeFunction('__yeetProjectAgents', projectAgents)
  await page.exposeFunction('__yeetProjectConversation', projectConversation)
  await page.exposeFunction('__yeetProjectComposer', projectComposer)
  await page.exposeFunction('__yeetProjectSettings', projectSettings)
  await page.exposeFunction('__yeetProjectToolbar', projectToolbar)
  await page.route('**/api/auth/status', async (route) => {
    await route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({ required: false, authenticated: true, key: false, passkey: false }),
    })
  })

  await page.route('**/api/protocol', async (route) => {
    await route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        version: 1,
        minVersion: 1,
        maxVersion: 1,
        websocket: '/api/ws',
        features: ['attachments-v1', 'files-v1'],
      }),
    })
  })

  await page.addInitScript((shellNodes) => {
    // Generated by Rust UI: this mock supplies projections without duplicating
    // application transition rules in TypeScript.
    let uiNode = 0
    let uiRevision = 0
    const initialState = {
      conversation_revision: 1,
      conversation: [
        { id: 'u1', kind: { type: 'user', content: 'Inspect the **remote UI** and keep it responsive.' } },
        {
          id: 'a1',
          kind: {
            type: 'assistant',
            content: '## Interface ready\n\nThe semantic browser frontend is connected.\n\n```ts\nconst transport = "websocket"\nconsole.log(transport)\n```',
          },
        },
        {
          id: 'r1',
          kind: {
            type: 'reasoning',
            content: 'I checked the semantic state and selected a responsive layout.',
            summary: 'Checked state and responsive layout',
          },
        },
        {
          id: 'act1',
          kind: {
            type: 'activity',
            activity: { phase: 'running', title: 'Inspecting workspace', detail: 'web/src', run_id: 'run-1' },
          },
        },
        {
          id: 'tool1',
          kind: {
            type: 'toolCall',
            toolCall: {
              id: 'tool1',
              name: 'read_file',
              arguments: '{"path":"web/src/App.tsx"}',
              status: 'completed',
              durationMs: 82,
              result: 'App.tsx loaded successfully',
            },
          },
        },
        { id: 'skill1', kind: { type: 'skill', name: 'frontend-review', content: 'Responsive checks enabled.', status: 'loaded' } },
        { id: 'mcp1', kind: { type: 'mcp', server: 'Yeet-KY', name: 'list_files', content: 'web/src', isError: false } },
        { id: 'sys1', kind: { type: 'system', content: 'Remote protocol v1 established.' } },
      ],
      active_assistant_entry_id: null,
      active_assistant_text: '',
      active_activity_entry_id: 'act1',
      active_reasoning_entry_id: null,
      active_reasoning_text: '',
      active_reasoning_summary: '',
      is_streaming: false,
      goal_mode: false,
      error_message: null,
      active_model: 'gpt-5.6-sol',
      active_reasoning_level: 'high',
      active_model_context_length: 200000,
      current_context_tokens: 42000,
      token_usage: { input_tokens: 42000, output_tokens: 2600 },
      credit_usage: 0,
      pending_shell_permission: null,
      pending_native_app_permission: null,
      available_models: ['gpt-5.6-sol', 'gpt-5.6-luna'],
      is_loading_models: false,
      saved_sessions: [
        { id: 'session-a', title: 'Remote WebUI', updated_at: new Date().toISOString(), model: 'gpt-5.6-sol', message_count: 8 },
        { id: 'session-b', title: 'Protocol review', updated_at: new Date(Date.now() - 3600000).toISOString(), model: 'gpt-5.6-luna', message_count: 4 },
      ],
      known_workspaces: [
        { id: '/Users/test/Code/Rust/Yeet', path: '/Users/test/Code/Rust/Yeet', display_name: 'Yeet', updated_at: new Date().toISOString(), session_count: 2, is_current: true },
        { id: '/Users/test/Code/Rust/AnotherProject', path: '/Users/test/Code/Rust/AnotherProject', display_name: 'AnotherProject', updated_at: new Date(Date.now() - 7200000).toISOString(), session_count: 1, is_current: false },
      ],
      current_session_id: 'session-a',
      active_run_id: 'run-1',
      available_capabilities: [
        { id: 'mcp:yeet', kind: 'mcp', name: 'Yeet MCP', description: 'Workspace execution tools', enabled: true },
        { id: 'skill:review', kind: 'skill', name: 'Review', description: 'Review frontend changes', enabled: false },
      ],
      is_loading_capabilities: false,
      auth_providers: [
        {
          provider: 'openai', authenticated: true, method: 'oauth', expires_at: null, error: null,
          usage: {
            provider: 'openai', available: true, source: 'api', fetchedAt: new Date().toISOString(), plan: 'team', message: null,
            windows: [{ id: 'five-hour', label: '5 hour', usedPercent: 31, remainingPercent: 69, resetsAt: null }],
          },
        },
      ],
      auth_notice: null,
      auth_working: false,
      provider_configurations: [{ id: 'local', base_url: 'http://127.0.0.1:11434/v1', require_api_key: false, header_count: 0 }],
      providers_notice: null,
      providers_working: false,
      openai_flex: false,
      foundation_memory_enabled: true,
      foundation_memory_server: 'foundation',
      foundation_memory_connected: true,
      settings_notice: null,
      settings_working: false,
      sandbox_settings: {
        preset: 'balanced', execution_mode: 'sandboxed', auto_approve: false, workspace_mode: 'all', workspace_paths: [], scratch_writable: true,
        network_allow: [{ host: 'api.openai.com', port: 443 }],
        environment: [{ key: 'RUST_LOG', value: 'info' }],
        secret_ids: ['OPENAI_API_KEY'],
        limits: { wall_time_seconds: 300, max_stdout_bytes: 1048576, max_stderr_bytes: 1048576, max_memory_bytes: 2147483648, max_processes: 32 },
      },
      sandbox_notice: null,
      sandbox_working: false,
      debate: null,
    }

    type Message = Record<string, unknown>
    const sockets: MockSocket[] = []
    const sent: Message[] = []
    const generatedClientId = `pw-${crypto.randomUUID()}`
    let forceFreshHandshake = false

    let agentUiState: Record<string, unknown> | undefined
    let agentsRevision = 0
    let harnessState: Record<string, unknown> = initialState
    let agentQueue = Promise.resolve()
    const project = (socket: MockSocket, action?: unknown) => {
      agentQueue = agentQueue.then(async () => {
        const host = window as unknown as {
          __yeetProjectAgents(input: unknown): Promise<{ ui_state: Record<string, unknown>; view: unknown; effect: { command?: unknown } }>
        }
        const result = await host.__yeetProjectAgents({ state: harnessState, ui_state: agentUiState, action })
        agentUiState = result.ui_state
        if (result.effect.command) sent.push({ type: 'command', version: 1, command: result.effect.command })
        socket.emit({ type: 'ui_agents', version: 1, agents_revision: ++agentsRevision, view: result.view, effect: result.effect })
      })
    }

    let conversationUiState: Record<string, unknown> | undefined
    let conversationRevision = 0
    let conversationQueue = Promise.resolve()
    const projectConversation = (socket: MockSocket, action?: unknown) => {
      conversationQueue = conversationQueue.then(async () => {
        const host = window as unknown as {
          __yeetProjectConversation(input: unknown): Promise<{ ui_state: Record<string, unknown>; view: unknown; effect: { command?: unknown } }>
        }
        const result = await host.__yeetProjectConversation({ state: harnessState, ui_state: conversationUiState, action })
        conversationUiState = result.ui_state
        if (result.effect.command) sent.push({ type: 'command', version: 1, command: result.effect.command })
        socket.emit({ type: 'ui_conversation', version: 1, conversation_revision: ++conversationRevision, view: result.view, effect: result.effect })
      })
    }

    let composerUiState: Record<string, unknown> | undefined
    let composerRevision = 0
    let composerWorkspace = '/Users/test/Code/Rust/Yeet'
    let unsavedGeneration = 0
    let composerQueue = Promise.resolve()
    const projectComposerUi = (socket: MockSocket, action?: unknown) => {
      composerQueue = composerQueue.then(async () => {
        const host = window as unknown as {
          __yeetProjectComposer(input: unknown): Promise<{ ui_state: Record<string, unknown>; view: unknown; effect: unknown; command?: unknown }>
        }
        const result = await host.__yeetProjectComposer({ state: harnessState, ui_state: composerUiState, action,
          environment: { context: { workspace: composerWorkspace, session_id: harnessState.current_session_id ?? null, unsaved_generation: unsavedGeneration },
            available: true, supported_destinations: ['models', 'sessions', 'settings', 'permissions', 'auth', 'providers', 'capabilities'], allow_commands_while_streaming: false } })
        composerUiState = result.ui_state
        if (result.command) {
          sent.push({ type: 'command', version: 1, command: result.command })
          if ((result.command as { type?: string }).type === 'new_session') unsavedGeneration++
        }
        socket.emit({ type: 'ui_composer', version: 1, composer_revision: ++composerRevision, view: result.view, effect: result.effect })
      })
    }

    let settingsUiState: Record<string, unknown> | undefined
    let settingsRevision = 0
    let settingsQueue = Promise.resolve()
    const projectSettingsUi = (socket: MockSocket, action?: unknown) => {
      settingsQueue = settingsQueue.then(async () => {
        const host = window as unknown as {
          __yeetProjectSettings(input: unknown): Promise<{ ui_state: Record<string, unknown>; view: unknown; effect: unknown; command?: unknown }>
        }
        const result = await host.__yeetProjectSettings({ state: harnessState, ui_state: settingsUiState, action, environment: {} })
        settingsUiState = result.ui_state
        if (result.command) sent.push({ type: 'command', version: 1, command: result.command })
        socket.emit({ type: 'ui_settings', version: 1, settings_revision: ++settingsRevision, view: result.view, effect: result.effect })
      })
    }

    let toolbarQueue = Promise.resolve()
    const projectToolbarUi = (socket:MockSocket,action?:unknown) => {
      toolbarQueue=toolbarQueue.then(async()=>{
        const host=window as unknown as {__yeetProjectToolbar(input:unknown):Promise<{projection:{state:Record<string,unknown>;view:unknown;toolbar:unknown};command?:unknown}>}
        const result=await host.__yeetProjectToolbar({state:harnessState,shell:shellNodes[uiNode].state,action})
        if(result.command){sent.push({type:'command',version:1,command:result.command});if((result.command as {type?:string}).type==='new_session'){unsavedGeneration++;projectComposerUi(socket)}}
        const next=shellNodes.findIndex(node=>JSON.stringify(node.state)===JSON.stringify(result.projection.state))
        if(next>=0)uiNode=next
        socket.emit({type:'ui_state',version:1,ui_revision:++uiRevision,state:result.projection.state,view:result.projection.view,toolbar:result.projection.toolbar})
      })
    }

        const mockEntries: Record<string, Array<Record<string, unknown>>> = {
      '': [
        { name: 'docs', path: 'docs', directory: true, size: 160, items: 2, modified: 1790000000, status: null },
        { name: 'src', path: 'src', directory: true, size: 192, items: 2, modified: 1791300000, status: ' M' },
        { name: 'README.md', path: 'README.md', directory: false, size: 2150, items: null, modified: 1790000000, status: null },
      ],
      src: [
        { name: 'limiter.ts', path: 'src/limiter.ts', directory: false, size: 2148, items: null, modified: 1791300000, status: ' M' },
        { name: 'index.ts', path: 'src/index.ts', directory: false, size: 640, items: null, modified: 1790000000, status: null },
      ],
      docs: [],
    }
    function mockFiles(path: string, selected: string | null) {
      const entries = mockEntries[path] ?? []
      const file = entries.find(entry => entry.path === selected)
      return {
        root: 'Yeet', path, parent: path ? '' : null, branch: 'main', entries,
        selected: file ? selected : null,
        info: file ? { path: selected, name: file.name, size: file.size, modified: file.modified, created: file.modified,
          permissions: 'rw-r--r--', lines: 71, status: file.status, added: file.status ? 11 : null, removed: file.status ? 4 : null } : null,
      }
    }
    const mockPatch = [
      'diff --git a/src/limiter.ts b/src/limiter.ts', 'index 1..2 100644', '--- a/src/limiter.ts', '+++ b/src/limiter.ts',
      '@@ -10,5 +10,6 @@ class TokenBucket {', '   refill(now: number) {', '-    const seconds = Math.floor(now / 1000)',
      '+    const seconds = now / 1000', '+    this.tokens = Math.min(this.cap, this.tokens + seconds * this.rate)', '   }',
    ]
    function mockChanges(file: string | null, full: boolean) {
      return {
        root: 'Yeet', branch: 'main',
        files: [
          { path: 'src/limiter.ts', status: ' M', added: 2, removed: 1 },
          { path: 'docs/notes.md', status: '??', added: 3, removed: 0 },
        ],
        selected: file ?? 'src/limiter.ts', full, patch: mockPatch, message: null,
      }
    }


    class MockSocket extends EventTarget {
      static readonly CONNECTING = 0
      static readonly OPEN = 1
      static readonly CLOSING = 2
      static readonly CLOSED = 3
      readonly CONNECTING = 0
      readonly OPEN = 1
      readonly CLOSING = 2
      readonly CLOSED = 3
      readyState = MockSocket.CONNECTING
      binaryType: BinaryType = 'blob'
      bufferedAmount = 0
      extensions = ''
      protocol = 'yeet.remote.v1'
      url: string
      onopen: ((this: WebSocket, ev: Event) => unknown) | null = null
      onclose: ((this: WebSocket, ev: CloseEvent) => unknown) | null = null
      onerror: ((this: WebSocket, ev: Event) => unknown) | null = null
      onmessage: ((this: WebSocket, ev: MessageEvent) => unknown) | null = null

      constructor(url: string | URL) {
        super()
        this.url = String(url)
        sockets.push(this)
        setTimeout(() => {
          this.readyState = MockSocket.OPEN
          this.dispatchEvent(new Event('open'))
        }, 0)
      }

      send(data: string | ArrayBufferLike | Blob | ArrayBufferView) {
        const message = JSON.parse(String(data)) as Message
        sent.push(message)
        if (message.type === 'hello') {
          queueMicrotask(() => {
            const cursor = typeof message.last_sequence === 'number' ? message.last_sequence : null
            const revision = typeof message.last_revision === 'number' ? message.last_revision : 1
            const requestedClientId = typeof message.client_id === 'string' ? message.client_id : null
            const resumed = !forceFreshHandshake && cursor != null && requestedClientId != null
            const clientId = requestedClientId ?? generatedClientId
            const sessionId = typeof message.session_id === 'string' ? message.session_id : 'session-a'
            const workspace = typeof message.workspace === 'string' && message.workspace
              ? message.workspace
              : '/Users/test/Code/Rust/Yeet'
            composerWorkspace = workspace
            forceFreshHandshake = false
            this.emit({ type: 'welcome', version: 1, client_id: clientId, workspace, session_id: sessionId, sequence: cursor ?? 0, revision, resumed })
            if (!resumed) {
              const state = {
                ...initialState,
                known_workspaces: initialState.known_workspaces.map((item) => ({ ...item, is_current: item.path === workspace })),
              }
              this.emit({ type: 'snapshot', version: 1, sequence: 1, revision: 1, state })
            }
            this.emitUi()
            project(this)
            projectConversation(this)
            projectComposerUi(this)
            projectSettingsUi(this)
          })
        } else if (message.type === 'workspace_files_request') {
          const view = mockFiles(String(message.path ?? ''), (message.selected as string | null) ?? null)
          queueMicrotask(() => this.emit({ type: 'workspace_files', version: 1, request_id: message.request_id, view }))
        } else if (message.type === 'workspace_changes_request') {
          const view = mockChanges((message.file as string | null) ?? null, Boolean(message.full))
          queueMicrotask(() => this.emit({ type: 'workspace_changes', version: 1, request_id: message.request_id, view }))
        } else if (message.type === 'ui_toolbar_action') {
          projectToolbarUi(this,message.action)
        } else if (message.type === 'ui_settings_action') {
          projectSettingsUi(this, message.action)
        } else if (message.type === 'ui_composer_action') {
          projectComposerUi(this, message.action)
        } else if (message.type === 'ui_conversation_action') {
          projectConversation(this, message.action)
        } else if (message.type === 'ui_agent_action') {
          project(this, message.action)
        } else if (message.type === 'ui_action') {
          const action = message.action as { type: string; layout?: string }
          const key = action.type === 'set_layout' ? `set_layout:${action.layout}` : action.type
          const node = shellNodes[uiNode]
          const next = (node.transitions as Record<string, number>)[key]
          if (next !== undefined) {
            uiNode = next
            uiRevision += 1
            queueMicrotask(() => this.emitUi())
          }
        }
      }

      emitUi() {
        const node = shellNodes[uiNode]
        projectToolbarUi(this)
      }

      close(code = 1000, reason = '') {
        if (this.readyState === MockSocket.CLOSED) return
        this.readyState = MockSocket.CLOSED
        this.dispatchEvent(new CloseEvent('close', { code, reason, wasClean: true }))
      }

      emit(message: Message) {
        if (message.type === 'snapshot') harnessState = message.state as Record<string, unknown>
        if (message.type === 'state_update') {
          harnessState = { ...harnessState, ...(message.patch as Record<string, unknown>) }
          project(this)
        }
        if (message.type === 'conversation_reset') harnessState.conversation = message.conversation
        if (message.type === 'conversation_entry' || message.type === 'tool_update' || message.type === 'activity_update') {
          const entries = (harnessState.conversation ?? []) as Array<{ id: string }>
          const entry = message.entry as { id: string }
          const index = entries.findIndex(item => item.id === entry.id)
          harnessState.conversation = index < 0 ? [...entries, entry] : entries.map((item, i) => i === index ? entry : item)
        }
        if (message.type === 'reasoning_delta' || message.type === 'assistant_delta') {
          const prefix = message.type === 'reasoning_delta' ? 'reasoning' : 'assistant'
          const field = prefix === 'reasoning' && message.summary ? 'summary' : 'text'
          const key = `active_${prefix}_${field}`
          harnessState[key] = message.reset ? message.content : String(harnessState[key] ?? '') + String(message.delta ?? '')
          harnessState[`active_${prefix}_entry_id`] = message.entry_id
          harnessState.is_streaming = true
        }
        if (message.type === 'state_update' || message.type === 'snapshot') { projectComposerUi(this); projectSettingsUi(this); projectToolbarUi(this) }
        if (['state_update', 'snapshot', 'conversation_reset', 'conversation_entry', 'tool_update', 'activity_update', 'reasoning_delta', 'assistant_delta'].includes(String(message.type))) projectConversation(this)
        this.dispatchEvent(new MessageEvent('message', { data: JSON.stringify(message) }))
      }
    }

    Object.defineProperty(window, 'WebSocket', { configurable: true, writable: true, value: MockSocket })
    Object.assign(window, {
      __yeetSent: sent,
      __yeetEmit: (message: Message) => sockets.at(-1)?.emit(message),
      __yeetDisconnect: () => sockets.at(-1)?.close(1006, 'test disconnect'),
      __yeetRestart: () => {
        forceFreshHandshake = true
        sockets.at(-1)?.close(1012, 'backend restart')
      },
    })
  }, shellFixtures)
}