import {expect,test} from '@playwright/test'
import {installMockRemote} from './mockRemote'
test('shared toolbar keeps live response choices available and interrupts through composer policy',async({page})=>{
 await installMockRemote(page);await page.goto('/');await expect(page.getByText('Interface ready')).toBeVisible()
 await page.getByRole('button',{name:'Quick settings'}).click()
 const panel=page.locator('.quick-panel')
 await panel.getByRole('switch',{name:'Goal mode'}).click()
 const commands=()=>page.evaluate(()=>(window as unknown as {__yeetSent:{type:string;command?:{type:string;enabled?:boolean}}[]}).__yeetSent.filter(item=>item.type==='command').map(item=>item.command))
 await expect.poll(commands).toContainEqual({type:'set_goal',enabled:true})
 await page.evaluate(()=>{(window as unknown as {__yeetEmit:(message:unknown)=>void}).__yeetEmit({type:'state_update',version:1,sequence:2,revision:2,patch:{is_streaming:true}})})
 await expect(panel.getByText('Working',{exact:true})).toBeVisible()
 await expect(panel.getByRole('combobox',{name:'Reasoning'})).toBeEnabled()
 await panel.getByRole('combobox',{name:'Reasoning'}).selectOption('medium')
 await expect.poll(commands).toContainEqual({type:'select_reasoning',level:'medium'})
 await page.getByRole('button',{name:'Close controls'}).click()
 const interrupt=page.getByRole('button',{name:'Interrupt run'})
 if(await interrupt.isVisible())await interrupt.click();else await page.getByRole('button',{name:'Stop',exact:true}).click()
 await expect.poll(commands).toContainEqual({type:'interrupt'})
})
test('shared header preserves local navigation offline while preventing runtime actions',async({page})=>{
 await installMockRemote(page);await page.goto('/');await expect(page.getByText('Interface ready')).toBeVisible()
 await page.getByRole('button',{name:'New chat',exact:true}).click()
 await expect.poll(()=>page.evaluate(()=>(window as unknown as {__yeetSent:{type:string;command?:{type:string}}[]}).__yeetSent.filter(item=>item.command?.type==='new_session').length)).toBe(1)
 await page.evaluate(()=>window.dispatchEvent(new Event('offline')))
 await expect(page.getByRole('button',{name:'New chat',exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:'Quick settings'})).toBeEnabled()
 await page.getByRole('button',{name:'Quick settings'}).click()
 await expect(page.locator('.quick-panel').getByRole('switch',{name:'Goal mode'})).toBeDisabled()
})
